@startuml casoscoffeshop
left to right direction
actor "Estudiante" as est
actor "Administrador Cafeteria" as admin
actor "Cajero" as cajero

rectangle "Sistemas de Pedidos CoffeeShop"{
    usecase "Iniciar Sesion" as UC1
    usecase "Realizar Pedido" as UC2
    usecase "Listar Pedidos" as UC3
}

est --> UC1 
est --> UC2
est --> UC3
admin --> UC1
admin --> UC2
admin --> UC3

UC1 <-- cajero
UC3 <-- cajero

@enduml